In [15]:
import numpy as np
x = [3, 5,6]
y = [2, 5,7]
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3, 5, 6]
[2, 5, 7]
Comparison - greater
[ True False False]
Comparison - greater_equal
[ True  True False]
Comparison - less
[False False  True]
Comparison - less_equal
[False  True  True]


In [16]:
evens = [x for x in range(30,70) if x%2 == 0]
print(evens)

[30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68]


In [60]:
a=np.eye(3,dtype="int64")
print("identity matrix with order 3\n",a)

identity matrix with order 3
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [45]:
import numpy
vec=np.arange(21)
vec[(vec>9) & (vec<15)]*=-1
print(vec)

[  0   1   2   3   4   5   6   7   8   9 -10 -11 -12 -13 -14  15  16  17
  18  19  20]


In [59]:
import numpy as np
k=np.eye(5,dtype="int64")
np.fill_diagonal(k, [1,2,3,4,5])
print("identity matrix with 1,2,3,4,5 as diagonal\n",k)

identity matrix with 1,2,3,4,5 as diagonal
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [58]:
import numpy as np
a=np.matrix('1 2 3 4;2 3 4 5;3 4 3 5')
print("sum of elements:\n",np.sum(a))
print("sum of elements column wise\n",np.sum(a,axis=0))
print("sum of elements row wise\n",np.sum(a,axis=1))

sum of elements:
 39
sum of elements column wise
 [[ 6  9 10 14]]
sum of elements row wise
 [[10]
 [14]
 [15]]


In [19]:
a=np.matrix('1 2 3;4 5 6;3 2 4')
ar=np.array(a)
print("array is:",a)
file=open("file1.txt","w")
c=str(ar)
file.write(c)
file.close()
file=open("file1.txt","r")
print("file1.txt:\n",file.read())
file.close()

array is: [[1 2 3]
 [4 5 6]
 [3 2 4]]
file1.txt:
 [[1 2 3]
 [4 5 6]
 [3 2 4]]


In [21]:
a=[2,3,4,5]
b=[4,3,7,8]
print(np.equal(a,b))

[False  True False False]


In [57]:
a=np.random.randint(4,size=(4,4))
print("matrix is:\n",a)
a[[-1,0]]=a[[0,-1]]
print("first and last row swapped:\n",a)

matrix is:
 [[3 2 2 2]
 [3 2 1 3]
 [0 3 0 1]
 [1 3 2 0]]
first and last row swapped:
 [[1 3 2 0]
 [3 2 1 3]
 [0 3 0 1]
 [3 2 2 2]]


In [55]:
a=[1,2,3,4]
print("first array is:      ",a)
b=[3,4,5,8]
print("second array is:     ",b)
c=np.multiply(a,b)
print("Multiplied array is:",c)

first array is:       [1, 2, 3, 4]
second array is:      [3, 4, 5, 8]
Multiplied array is: [ 3  8 15 32]
